import { Pool } from "pg";
const globalUsers = globalThis as unknown as { tfrsUsersPool?: Pool };
function config(){
  if(process.env.USER_DATABASE_URL) return {connectionString:process.env.USER_DATABASE_URL,ssl:process.env.USER_DATABASE_SSL==="true"?{rejectUnauthorized:false}:undefined};
  if(process.env.NODE_ENV === "production" && process.env.DATABASE_URL) return {connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==="true"?{rejectUnauthorized:false}:undefined};
  return {host:process.env.DB_HOST||"127.0.0.1",port:Number(process.env.DB_PORT||5432),user:process.env.DB_USER||"postgres",password:process.env.DB_PASSWORD||"postgres",database:process.env.DB_NAME||"spc_government_systems"};
}
export const userDb=globalUsers.tfrsUsersPool??new Pool({...config(),max:5});
if(process.env.NODE_ENV!=="production")globalUsers.tfrsUsersPool=userDb;
export async function ensureSystemUsers(){await userDb.query(`CREATE TABLE IF NOT EXISTS system_users (id BIGSERIAL PRIMARY KEY,full_name VARCHAR(160) NOT NULL,email VARCHAR(255) NOT NULL UNIQUE,password_hash TEXT NOT NULL,requested_office VARCHAR(20) NOT NULL CHECK (requested_office IN ('CTMO','FINANCE')),approved_office VARCHAR(20) NULL CHECK (approved_office IN ('CTMO','FINANCE','BOTH')),role VARCHAR(80) NULL,status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','ACTIVE','DISABLED','REJECTED')),last_login TIMESTAMP NULL,approved_at TIMESTAMP NULL,approved_by VARCHAR(255) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)`);await userDb.query(`CREATE INDEX IF NOT EXISTS idx_system_users_status ON system_users(status)`);await userDb.query(`CREATE TABLE IF NOT EXISTS password_change_requests (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES system_users(id) ON DELETE CASCADE,email VARCHAR(255) NOT NULL,office VARCHAR(20) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'PENDING',requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,reviewed_at TIMESTAMP NULL,reviewed_by VARCHAR(255) NULL,completed_at TIMESTAMP NULL,proposed_password_hash TEXT NULL)`);await userDb.query(`ALTER TABLE password_change_requests ADD COLUMN IF NOT EXISTS proposed_password_hash TEXT NULL`);await userDb.query(`DO $$ BEGIN IF EXISTS(SELECT 1 FROM pg_constraint WHERE conname='password_change_requests_status_check' AND pg_get_constraintdef(oid) NOT LIKE '%SUBMITTED%') THEN ALTER TABLE password_change_requests DROP CONSTRAINT password_change_requests_status_check; END IF; IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='password_change_requests_status_check') THEN ALTER TABLE password_change_requests ADD CONSTRAINT password_change_requests_status_check CHECK(status IN ('PENDING','APPROVED','SUBMITTED','REJECTED','COMPLETED')); END IF; END $$`);await userDb.query(`CREATE INDEX IF NOT EXISTS idx_password_requests_status ON password_change_requests(status,requested_at DESC)`);await userDb.query(`CREATE TABLE IF NOT EXISTS user_device_sessions (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES system_users(id) ON DELETE CASCADE,device_id VARCHAR(80) NOT NULL,office VARCHAR(20) NOT NULL,device_name VARCHAR(180) NOT NULL,browser VARCHAR(80) NOT NULL,ip_address VARCHAR(80) NULL,first_seen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,device_id,office))`);await userDb.query(`CREATE INDEX IF NOT EXISTS idx_user_devices ON user_device_sessions(user_id,last_seen DESC)`)}
