import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import { z } from "zod";
import { verifySession } from "@/lib/auth";
import { userDb } from "@/lib/user-db";

async function admin(){return verifySession((await cookies()).get("tfrs_session")?.value)}
async function ensure(){await userDb.query(`CREATE TABLE IF NOT EXISTS officer_restoration_requests (id BIGSERIAL PRIMARY KEY,call_sign VARCHAR(50) NOT NULL,officer_name VARCHAR(180) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'PENDING',requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,reviewed_at TIMESTAMP NULL,reviewed_by VARCHAR(255) NULL,CONSTRAINT officer_restoration_status_check CHECK(status IN ('PENDING','APPROVED','REJECTED')))`);await userDb.query(`CREATE INDEX IF NOT EXISTS idx_officer_restoration_requests_status ON officer_restoration_requests(status,requested_at DESC)`)}
const schema=z.object({id:z.coerce.number().int().positive(),action:z.enum(["APPROVE","REJECT"])});

export async function GET(){const a=await admin();if(!a||(a.role!=="Super Admin"&&!a.permissions.includes("*")))return NextResponse.json({error:"Super Admin access is required."},{status:403});await ensure();const result=await userDb.query(`SELECT id,call_sign "callSign",officer_name "officerName",status,TO_CHAR(requested_at,'YYYY-MM-DD HH24:MI') "requestedAt",COALESCE(reviewed_by,'—') "reviewedBy" FROM officer_restoration_requests ORDER BY CASE WHEN status='PENDING' THEN 0 ELSE 1 END,requested_at DESC`);return NextResponse.json(result.rows,{headers:{"Cache-Control":"no-store"}})}

export async function PATCH(request:Request){const a=await admin();if(!a||(a.role!=="Super Admin"&&!a.permissions.includes("*")))return NextResponse.json({error:"Super Admin access is required."},{status:403});try{const input=schema.parse(await request.json());await ensure();const client=await userDb.connect();try{await client.query("BEGIN");const pending=await client.query(`SELECT call_sign FROM officer_restoration_requests WHERE id=$1 AND status='PENDING' FOR UPDATE`,[input.id]);if(!pending.rowCount){await client.query("ROLLBACK");return NextResponse.json({error:"This restoration request is no longer pending."},{status:409})}const status=input.action==="APPROVE"?"APPROVED":"REJECTED";if(status==="APPROVED"){const officer=await client.query(`UPDATE officers SET archived=FALSE WHERE call_sign=$1 RETURNING call_sign`,[pending.rows[0].call_sign]);if(!officer.rowCount){await client.query("ROLLBACK");return NextResponse.json({error:"The archived officer record was not found."},{status:404})}}await client.query(`UPDATE officer_restoration_requests SET status=$1,reviewed_at=NOW(),reviewed_by=$2 WHERE id=$3`,[status,a.email,input.id]);await client.query("COMMIT");return NextResponse.json({ok:true,message:status==="APPROVED"?"Officer restoration approved.":"Officer restoration rejected."})}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}}catch(error){console.error("Officer restoration review failed",error);return NextResponse.json({error:"Unable to review the restoration request."},{status:400})}}
