"use client";
import { useState } from "react";
import { Building2, Check, FileText, KeyRound, Plus, Save, Settings2, ShieldCheck, SlidersHorizontal, WalletCards } from "lucide-react";
const roles: {name:string;description:string;scope:string;users:number;permissions:number;status:string}[] = [];
const permissionGroups: {group:string;items:string[]}[] = [];
import { Button, PageHeader, Status } from "./ui";
export function RolesPage(){const [selected,setSelected]=useState('Super Admin');const [saved,setSaved]=useState(false);return <div className="page"><PageHeader title="Roles & permissions" description="Manage role-based access and office scope across the system." actions={<Button><Plus/> Create custom role</Button>}/>{saved&&<div className="success-note">Permissions saved and audit event recorded.<button onClick={()=>setSaved(false)}>×</button></div>}<div className="role-layout"><section className="panel role-list"><div className="panel-title"><div><h2>System roles</h2><p>{roles.length} configured roles</p></div></div>{roles.map(r=><button className={selected===r.name?'active':''} key={r.name} onClick={()=>setSelected(r.name)}><span className="role-shield"><ShieldCheck/></span><div><b>{r.name}</b><small>{r.description}</small><em>{r.users} users · {r.scope}</em></div><Status>{r.status}</Status></button>)}</section><section className="panel permissions-panel"><div className="permission-head"><div><span className="role-shield large"><KeyRound/></span><div><h2>{selected}</h2><p>Configure module actions and administrative access.</p></div></div><label className="switch-label">Role active <input type="checkbox" defaultChecked/><i/></label></div><div className="office-scope"><span>Office access</span><label><input type="radio" name="scope" defaultChecked/> All offices</label><label><input type="radio" name="scope"/> Assigned office only</label></div><div className="permission-groups">{permissionGroups.map(g=><div key={g.group}><div><b>{g.group}</b><button>Select all</button></div>{g.items.map(i=><label key={i}><input type="checkbox" defaultChecked={selected==='Super Admin'||Math.random()>.3}/><span><Check/>{i}</span></label>)}</div>)}</div><div className="sticky-actions"><span>Changes are logged in the audit trail.</span><Button onClick={()=>setSaved(true)}><Save/> Save permissions</Button></div></section></div></div>}

const settingSections=[{title:'Office Management',desc:'Connected departments and system status',icon:Building2,items:[['BPLO connection','Active'],['CTMO connection','Active'],['Finance / CTO connection','Active']]},{title:'System Information',desc:'Application identity and support details',icon:Settings2,items:[['System name','Tricycle Franchising and Renewal System'],['Administrator email','admin@tfrs.gov.ph']]},{title:'Document Settings',desc:'Printing and permit defaults',icon:FileText,items:[["Mayor's Permit remarks",'Compliant with current franchise rules'],['Print paper size','A4']]},{title:'User Access Settings',desc:'Session and account policies',icon:KeyRound,items:[['Session expiration','8 hours'],['Failed login lockout','5 attempts']]},{title:'Franchise Rules',desc:'Ownership and renewal constraints',icon:SlidersHorizontal,items:[['Maximum owners','3'],['Active drivers per franchise','1'],['Renewal grace period','30 days']]},{title:'Payment Settings',desc:'Collection and OR behavior',icon:WalletCards,items:[['Payment verification','Required'],['Partial payments','Disabled']]}];
export function SettingsPage(){const [section,setSection]=useState('Office Management');const [saved,setSaved]=useState(false);const current=settingSections.find(s=>s.title===section)!;return <div className="page"><PageHeader title="System settings" description="Configure connected offices, access policies, business rules, and documents."/>{saved&&<div className="success-note">Settings saved successfully.<button onClick={()=>setSaved(false)}>×</button></div>}<div className="settings-layout"><aside className="panel settings-nav">{settingSections.map(s=><button key={s.title} className={section===s.title?'active':''} onClick={()=>setSection(s.title)}><s.icon/><span><b>{s.title}</b><small>{s.desc}</small></span></button>)}</aside><section className="panel settings-content"><div className="settings-title"><span className="report-icon"><current.icon/></span><div><h2>{current.title}</h2><p>{current.desc}</p></div></div><div className="settings-fields">{current.items.map(([label,value])=><label key={label}><span>{label}</span>{value==='Active'?<div className="setting-status"><i/> Connected and operational</div>:label==='Partial payments'?<select defaultValue={value}><option>Disabled</option><option>Enabled</option></select>:<input defaultValue={value}/>}<small>Changes apply system-wide and are audited.</small></label>)}</div><div className="settings-actions"><Button onClick={()=>setSaved(true)}><Save/> Save changes</Button></div></section></div></div>}
